### ISSUE TITLE
ctrl w

### ISSUE THREAD

**Issue by simdax** [iomonad/iomonad.el#9]
Kill region me donne ==> wrong type argument; commandp, copy

La lose

Il faut agir ctrouille : que fait Superman ??

**Comment by iomonad** [comment]
Dans la prochaine version je vais virer evil-mode, donc retour au basic avec le pure emacs. Nous allons pouvoir passer en mode tentacules.

**Comment by iomonad** [comment]
Le mauvais typage t'es retourne en mode visuel @simdax ?
